### PR TITLE
fix: make `kiosk.devices` and `kiosk.printers` work again

### LINKED ISSUE #120: `kiosk.devices` not working
## Steps to Reproduce
1. Open `kiosk-browser` with devtools
2. In devtools console, run `kiosk.devices.subscribe(console.log)`

## Expected Behavior
The call would succeed and device addition/removal would cause the device list to be logged.

## Actual Behavior
This error is thrown: `TypeError: kiosk.devices.subscribe is not a function`

## What's going on?
Exposing an object to the main world via `contextBridge.exposeInMainWorld` makes the object and all of its contained objects available, but none of the properties from any objects' `prototype` are available. For example:

```ts
// preload.ts
class Box<T> {
  value: T;

  constructor(value) {
    this.value = value;
  }

  toBox(): this {
    return this;
  }
}

contextBridge.exposeInMainWorld('box', new Box(1));
```

Accessing the global works fine:
```
box
> { value: 1 }
```

But trying to call a prototype method fails:
```
box.toBox()
> TypeError: box.toBox is not a function
```

## Solution
We can provide functions, but they need to be defined as "own properties" on the objects. Since we're not really using RxJS extensively in the apps, I think we should change the `kiosk.devices` API to be mostly compatible but simpler.

### PR DESCRIPTION
**Pull request by eventualbuddha**
Fixes #120 

Added a bare-bones integration test for devices and tested both `devices` and `printers` subscriptions in `about:blank` and `devices` in Election Manager. Requires this patch be applied in `vxsuite`:

```diff
diff --git a/libs/ui/src/hooks/use_devices.ts b/libs/ui/src/hooks/use_devices.ts
index 34a69360..c4828536 100644
--- a/libs/ui/src/hooks/use_devices.ts
+++ b/libs/ui/src/hooks/use_devices.ts
@@ -7,7 +7,6 @@ import {
   isPrecinctScanner,
 } from '@votingworks/utils';
 import { useEffect, useState } from 'react';
-import { map } from 'rxjs/operators';
 import useInterval from 'use-interval';
 import { useCancelablePromise } from './use_cancelable_promise';
 import { usePrevious } from './use_previous';
@@ -64,13 +63,13 @@ export function useDevices({ hardware, logger }: Props): Devices {
   const previousPrinters = usePrevious(allPrinters);
 
   useEffect(() => {
-    const hardwareStatusSubscription = hardware.devices
-      .pipe(map((devices) => Array.from(devices)))
-      .subscribe(setAllDevices);
+    const hardwareStatusSubscription = hardware.devices.subscribe((devices) => {
+      setAllDevices(Array.from(devices));
+    });
 
-    const printerStatusSubscription = hardware.printers
-      .pipe(map((printers) => Array.from(printers)))
-      .subscribe(setAllPrinters);
+    const printerStatusSubscription = hardware.printers.subscribe((devices) => {
+      setAllPrinters(Array.from(devices));
+    });
 
     return () => {
       hardwareStatusSubscription.unsubscribe();
```

### CODE REVIEW

**Review by benadida — APPROVED** [review]

File: src/utils/buildIpcMainForwardingObservable.ts [hunk 1]
```diff
@@ -11,23 +9,51 @@ const debug = makeDebug('kiosk-browser:client:ipc');
...
+  //   map(([, value]) => value),
+  //   tap((value) =>
+  //     debug('got value from IPC channel "%s": %O', channel, value),
+  //   ),
+  //   finalize(() => {
+  //     debug('unsubscribing from channel: %s', channel);
+  //     void ipcRenderer.invoke(channel, { subscribe: false });
+  //   }),
+  //   shareReplay({ refCount: true, bufferSize: 1 }),
+  // );
```
Comment (benadida) [inline src/utils/buildIpcMainForwardingObservable.ts:56]: remove?
